### PR TITLE
Adding a requirements.txt file for ease of installation in a virtualenv

### PR DESCRIPTION
**Pull request by jstnlef**
Referencing this issue: https://github.com/donnemartin/interactive-coding-challenges/issues/14

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi Justin, 

Is zmq really a requirement?  It seems pyzmq is sufficient...I'm able to run the notebooks without zmq.

Do you need zmq to run the notebooks on your system?

-Donne

**Comment by jstnlef** [comment]
Good question. It seemed to be when I was installing it the first time. I
will try removing it later today to see if it's actually necessary and push
any updates.

**Comment by jstnlef** [comment]
So I installed `ipython` using the instructions in the `README` and did a `pip freeze` based on that. Seem ok?

**Comment by donnemartin** [comment]
Looks good, thanks for the contribution Justin!

**Comment by donnemartin** [comment]
I updated the README with an installation method using your requirements.txt: 09d6703b23d21c9e84b94dd900432924c84d27d5

**Comment by jstnlef** [comment]
Excellent. Very nice.

**Pull request merged**
