### PR TITLE
Fix check_balance solution for a new test case

### PR DESCRIPTION
**Pull request by superxiao**
This fixes issue #35

### CODE REVIEW

**Comment by donnemartin** [comment]
@superxiao thanks for the pull request!  I hope to check it out in the next day or so.

**Comment by donnemartin** [comment]
@superxiao just want to follow up this is still on my TODO list, been a little tied up lately.  Hoping to get to it over the weekend.

**Comment by superxiao** [comment]
@donnemartin No worries. And thank you for your project which just helped me to get an onsite interview with one of the big names : )

**Comment by donnemartin** [comment]
@superxiao oh wow awesome, good luck!

**Comment by donnemartin** [comment]
@superxiao thanks for contribution :+1:

**Pull request merged**
