### PR TITLE
adds "reverse words in a string" challenge and its solution

### PR DESCRIPTION
**Pull request by muatik**

### CODE REVIEW

**Comment by donnemartin** [comment]
@muatik thanks again for the pull request!  I'll try to get a review by the weekend.

**Comment by muatik** [comment]
@donnemartin any update?

**Comment by donnemartin** [comment]
@muatik please check out the feedback in https://github.com/donnemartin/interactive-coding-challenges/pull/40, as much of it applies to this PR.

Also, I think the use of `split` considerably simplifies this classic interview problem.  What do you think of either either 1) adding an additional non-`split` solution or 2) tweaking the existing solution to not use `split`?

**Comment by donnemartin** [comment]
Hi @muatik, not sure if you're still interested in completing the changes suggested in this PR. I'll be closing it soon unless I hear back. Thanks.

**Comment by donnemartin** [comment]
Hi @muatik

I'm trying to clear out all PRs on this repo.  This PR hasn't had much activity in awhile, feel free to re-open it if you'd like to add additional commits to address the review comments.

-Donne

**Pull request closed without merging**
