### PR TITLE
Added group_ordered challenge

### PR DESCRIPTION
**Pull request by wdonahoe**
Added a challenge under array_strings/group_ordered. Includes challenge, solution with two algorithms, and a test file. Also added challenge to readme.

### CODE REVIEW

**Comment by donnemartin** [comment]
Awesome thanks for the pull request!  I'll try to review this some more in the evening.

**Comment by donnemartin** [comment]
William, just touching base--I haven't forgotten about this, hoping to have some time over the weekend for a review.

**Comment by wdonahoe** [comment]
Sure, no problem. Take your time!

On Fri, Jul 10, 2015 at 5:53 PM, Donne Martin <notifications@github.com>
wrote:

> William, just touching base--I haven't forgotten about this, hoping to
> have some time over the weekend for a review.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/donnemartin/interactive-coding-challenges/pull/9#issuecomment-120537816>
> .
>



-- 
William Donahoe
University of Delaware Class of 2015
Computer Science Major
Mathematics Minor

**Comment by donnemartin** [comment]
Hi William,

Thanks again for the pull request.  Here are a few comments to consider:

-When I ran the solution notebook the unit tests do not pass.  It seems you are not checking for a None input with your alternate solution.
-This seems to be a sorting challenge and might be better placed in the sorting category.  Can we move it to the section "Sorting and Searching"?
-The solution notebooks have a button "Edit Metadata" for each cell which is not present in the challenge notebooks or the other notebooks in the repo.  Can we remove them?
-The hyperlinks to the solution notebooks don't seem to point to the correct solution notebook.
-The code style could be updated to PEP-8: mostly there are whitespace issues around operators like commas.  I've found that http://pep8online.com/ is handy as I haven't yet seen a good solution for PEP-8 checks in notebooks.  With that said, some of the repo notebooks don't follow some PEP-8 guidelines, I'll submit a fix for those :)

-Donne

**Comment by wdonahoe** [comment]
Hi Donne,

- Tests should work now, and they're a little more descriptive.

- I've moved the folder into sorting/searching.

- As far as the hyperlinks go (in readme), they should be 404s right now
because I have them pointing to where the solution / challenge will reside
on your repo after the pull request, not to the location on my fork. I
assume that's the behavior you want.

- I've fixed the pep guidelines, except for one - line 22 in the default
solution being too long by 10 characters. Either I would need to change my
variable names to something less descriptive, e.g. "l", or add an ugly line
break.

- Removed "Edit Metadata"

I accidentally (foolishly) ran some of your solutions from my repo, so I'm
going to revert those files and then let me know if there are any more
issues.

Regards,







On Sat, Jul 11, 2015 at 6:31 AM, Donne Martin <notifications@github.com>
wrote:

> Hi William,
>
> Thanks again for the pull request. Here are a few comments to consider:
>
> -When I ran the solution notebook the unit tests do not pass. It seems you
> are not checking for a None input with your alternate solution.
> -This seems to be a sorting challenge and might be better placed in the
> sorting category. Can we move it to the section "Sorting and Searching"?
> -The solution notebooks have a button "Edit Metadata" for each cell which
> is not present in the challenge notebooks or the other notebooks in the
> repo. Can we remove them?
> -The hyperlinks to the solution notebooks don't seem to point to the
> correct solution notebook.
> -The code style could be updated to PEP-8: mostly there are whitespace
> issues around operators like commas. I've found that
> http://pep8online.com/ is handy as I haven't yet seen a good solution for
> PEP-8 checks in notebooks. With that said, some of the repo notebooks don't
> follow some PEP-8 guidelines, I'll submit a fix for those :)
>
> -Donne
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/donnemartin/interactive-coding-challenges/pull/9#issuecomment-120602975>
> .
>



-- 
William Donahoe
University of Delaware Class of 2015
Computer Science Major
Mathematics Minor

**Comment by donnemartin** [comment]
Hi William,

>Tests should work now, and they're a little more descriptive.
>I've moved the folder into sorting/searching.
>Removed "Edit Metadata"

Great!

>As far as the hyperlinks go...

The two hyperlinks might have tripped you up :)

The challenge notebook Algorithm section still has a link to the following:
https://github.com/donnemartin/interactive-coding-challenges/templates/foo_solution.ipynb

>I've fixed the pep guidelines, except for one - line 22 

Sounds good.

>I accidentally (foolishly) ran some of your solutions from my repo, so I'm
going to revert those files and then let me know if there are any more
issues.

No problem, although this might cause confusion on the version history.  What do you think about submitting another pull request with just the relevant code changes?  I suggest to work off a branch in your fork, load up just the relevant changes, then submit a pull request.

-Donne

**Comment by donnemartin** [comment]
Hi William,

Do you need any help moving forward with this pull request?  Let me know if there's some way I can pitch in.

-Donne

**Comment by donnemartin** [comment]
Hi William,

I'll place this in the "staging" directory for some tweaks and polishing. Please review the comments I made in this pull request.

Thanks for the contribution!

-Donne

**Pull request merged**
