### PR TITLE
Code concerning Issue #38

### PR DESCRIPTION
**Pull request by hashhar**
Improve compression by appending count only if count exceeds 2 ( #38 )

## Changed Files:
* `arrays_strings/compress/compress_challenge.ipynb`
* `arrays_strings/compress/compress_solution.ipynb`
* `arrays_strings/compress/test_compress.py`

## Chagenlog:
* The solution notebook and challenge notebook have updates titles and test cases.
* The solution notebook has changes made to the `compress_string` function with some helpful comments for explaining the changes

Even in case it is not pulled, do comment on how I did and what I could have done to do it better.

### CODE REVIEW

**Comment by hashhar** [comment]
Sorry for the two commits, it could have been done in one. (But I'm a commit hungry and streak hungry person :stuck_out_tongue: )

**Comment by muatik** [comment]
the time and space complexity of your implementation are O(n) and O(n), as you specified?

**Comment by hashhar** [comment]
No, I haven't checked those. Let me check.

**Comment by donnemartin** [comment]
@hashhar thanks for the pull request!  I'll try to review this in the next few days.

@muatik appreciate the review :+1:

**Comment by donnemartin** [comment]
@hashhar just a quick update...I haven't forgotten about this, I hope to get to it by the weekend.

**Comment by hashhar** [comment]
Thanks to let me know. Take your time. I have exams coming up anyway.

**Comment by donnemartin** [comment]
@hashhar thanks again for the PR, here are some thoughts:

The requirement change of "Improve compression by appending count only if count exceeds 2" makes a lot of sense, although it does make the solution a bit more complex.  Perhaps we should make it a 'follow-up' type question and add another solution as opposed to modifying the existing solution?

Problem: Compress a string such that 'AAABCCDDDD' becomes 'A3B1C2D4'. Only compress the string if it saves space.  What if you don't want to display 'B1' and instead want the output to be 'A3BC2D4'?

Here's a notebook with multiple solutions as a template:

http://nbviewer.ipython.org/github/donnemartin/interactive-coding-challenges/blob/master/arrays_strings/unique_chars/unique_chars_solution.ipynb

Additional comments:

* The use of tabs instead of spaces is making it hard for me to diff the solutions.  Can you use spaces instead?  Please check out the [style guide](https://github.com/donnemartin/interactive-coding-challenges/blob/master/CONTRIBUTING.md#maintain-consistent-style).
* I wonder if there's a way to reduce the number of times `compressed_string.append` is called from 6x.
* There's a `FIXME` comment left in the submission.

**Comment by hashhar** [comment]
Thanks for the feedback. I'll get back onto it.
It may take me some more time because I have my exams going on.

**Comment by donnemartin** [comment]
@hashhar no rush!

**Comment by hashhar** [comment]
I did all the required changes @donnemartin

**Comment by hashhar** [comment]
Fixed all of the issues you mentioned. Also, the `append` is only being called twice (only any one of the cases will be run) in any one of the 3 branch conditionals.

**Comment by donnemartin** [comment]
@hashhar thanks for the revisions!  I'll try to check it out within the next few days.

**Comment by donnemartin** [comment]
@hashhar sorry, fell behind on this from the holidays.  Just want to let you know it's still on my TODO list.

**Comment by hashhar** [comment]
@donnemartin Seems you are really busy. Just wanted to remind you.

**Comment by donnemartin** [comment]
@hashhar thanks for the ping, sorry it's taking awhile, this is still on my short-term radar.  I plan to circle back to this project very soon and invest a lot of time beefing it up, including clearing out pull requests.  Thanks!

**Comment by donnemartin** [comment]
Merged, thanks @hashhar!

**Pull request merged**
