### PR TITLE
Fixed links of all questions.

### PR DESCRIPTION
**Pull request by ShantanuKamath**
@donnemartin Please review this

### CODE REVIEW

**Comment by ShantanuKamath** [comment]
Added for graph_trees/graph_bfs too!

**Comment by ShantanuKamath** [comment]
Hi @donnemartin will look into them!

**Comment by ShantanuKamath** [comment]
Hi @donnemartin is this okay? I've squashed the commits into 1 and removed all the extra metadata. Used a package called nbstripout. Its stripped more than what was added by me. But maybe you can consider keeping files like that now? Do see the git diffs.

**Comment by ShantanuKamath** [comment]
So what it has essentially done is:
- Added a solution link, wherever missing or wrong. 
- Cleaned the notebooks to keep out all the extra metadata. Which in this case refers to the json keys that refer to keeping counts of execution and the outputs of the data. On referring to the way git and IPython NB are maintained by keeping only the source code and no account of the cells run or their outputs. There is module called nbstripout that does just this. https://pypi.python.org/pypi/nbstripout/0.2.0
Hope that clears it out?

**Comment by ShantanuKamath** [comment]
Any update on this?  @donnemartin

**Comment by donnemartin** [comment]
There are too many extraneous changes in this diff.  The only changes that should show up are the relevant link changes.

**Comment by eamanu** [comment]
Try with a new PR, with the correct commit @ShantanuKamath

**Comment by ShantanuKamath** [comment]
Okay will try again! :)

**Pull request closed without merging**
