### PR TITLE
Added n-pairs parentheses challenge

### PR DESCRIPTION
**Pull request by rishihot55**
I've implemented the **recursive n-pairs parentheses** challenge. The solution requires the use of an utility function using a auxiliary string and a result set to store all the solutions. 

Hopefully, there shouldn't be any problems. If this wasn't what you expected, I can modify it to suit your requirements.

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi Rishi,

Thanks for the pull request!  I hope to review and provide feedback within the next few days.

-Donne

**Comment by donnemartin** [comment]
Hi Rishi,

This is looking great, thanks for the challenge.  Here are some comments for consideration:

* It might be helpful to add some more detail to the algorithm discussion, as it is very similar (and in most cases identical) to the actual solution.
* For the time complexity, it seems you are saying this is catalan.  It might be helpful to add a link to this [wikipedia page](https://en.wikipedia.org/wiki/Catalan_number) as a reference.
* Do you know what the space complexity is?

-Donne

**Comment by rishihot55** [comment]
Hi Donne,
Thanks for the reply! I'll make sure to incorporate all those changes in my
next push.

On Sun, Aug 9, 2015 at 4:41 PM, Donne Martin <notifications@github.com>
wrote:

> Hi Rishi,
>
> This is looking great, thanks for the challenge. Here are some comments
> for consideration:
>
>    - It might be helpful to add some more detail to the algorithm
>    discussion, as it is very similar (and in most cases identical) to the
>    actual solution.
>    - For the time complexity, it seems you are saying this is catalan. It
>    might be helpful to add a link to this wikipedia page
>    <https://en.wikipedia.org/wiki/Catalan_number> as a reference.
>    - Do you know what the space complexity is?
>
> -Donne
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/donnemartin/interactive-coding-challenges/pull/30#issuecomment-129167495>
> .
>



-- 
Rishi Rajasekaran
NIT Trichy

**Comment by rishihot55** [comment]
Hi Donne,
I've updated the solution information with the following changes:
* I've given a textual description of the algorithm as well as a more explicit description involving the main cases
* I've updated the time complexity description with a link to the Catalan numbers wiki page.
* I've also included the space complexity info, which I checked to be O(n). Correct me if I'm wrong.

Hopefully that should be it for this problem. I'll also add another challenge once I get the time.
-Rishi

**Comment by donnemartin** [comment]
Good stuff, thanks Rishi!

**Pull request merged**
