### PR TITLE
Add a different solution to compress string challenge

### PR DESCRIPTION
**Pull request by janhak**
Hi Donne, 

I have been enjoying your interactive coding challenges quite a bit - thanks! 

I am not sure whether it is something you would like to see in the project but this is a different take on string compress challenge since at the moment answers to both basic and alternate challenge the answers are very similar in terms of mechanics.

Best Regards

Jan

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi Jan, 

Thanks for the pull request!  I'll try to review it this week.

-Donne

**Comment by donnemartin** [comment]
Hi Jan, interesting solution!  Could you please make the following tweaks?

* Update the authors list at the top of the notebook
* Make case consistent - suggest to start with upper case for each bullet point, unless it's a variable
* Fix typo: **Compres** blocks
* Run code through a linter such as http://pep8online.com/checkresult

Thanks!

**Comment by janhak** [comment]
Hi Donne, 

Thank you for the feedback. I made sure it is PEP8 compliant, incorporated author information and changed the commit message. Next time I will remember to put it through a linter. 

Many thanks

Jan

**Comment by donnemartin** [comment]
Thank you!

**Pull request merged**
