### PR TITLE
Simplify loop in max profit challenge

### PR DESCRIPTION
**Pull request by kagemusha**

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi @kagemusha this seems like a clever optimization.  I'm mobile at the moment and can't check, this passes unit tests?

**Comment by kagemusha** [comment]
@donnemartin yes it does

**Comment by hmeng1995** [comment]
i don't know




------------------ 原始邮件 ------------------
发件人: "Donne Martin";<notifications@github.com>;
发送时间: 2017年10月14日(星期六) 上午8:25
收件人: "donnemartin/interactive-coding-challenges"<interactive-coding-challenges@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [donnemartin/interactive-coding-challenges] max_profit_solution:simplify loop by popping first price (#214)




Hi @kagemusha this seems like a clever optimization.  I'm mobile at the moment and can't check, this passes unit tests?

**Comment by donnemartin** [comment]
@kagemusha thank you!

**Pull request merged**
