### PR TITLE
add "remove specified character in a given string" challenge and its solution

### PR DESCRIPTION
**Pull request by muatik**

### CODE REVIEW

**Comment by donnemartin** [comment]
@muatik thanks for the pull request!  I'll try to get a review by the weekend.

**Comment by donnemartin** [comment]
@muatik thanks again for the PR, here are some thoughts:

Thanks for adding the Pythonic solutions.  Could you provide their time and space complexities?

I like the benchmark section!

I think the solution notebook in particular could use some more polish.  Here are some suggestions:

* There are a couple typos: 'funciton', 'modidication'
* The solution notebook could use some additional formatting, check out existing notebooks as a template.  Examples:
    * Missing author info, title
    * Double bullets and capitalization in Algorithm section
    * Code header missing
    * Unit Tests header renamed

**Comment by donnemartin** [comment]
Hi @muatik, not sure if you're still interested in completing the changes suggested in this PR. I'll be closing it soon unless I hear back. Thanks.

**Comment by muatik** [comment]
hi @donnemartin , I am a little bit busy with my school these days, I will go back to this later.

**Comment by donnemartin** [comment]
No problem, thanks for the update.

**Comment by donnemartin** [comment]
Hi @muatik

I'm trying to clear out all PRs on this repo.  This PR hasn't had much activity in awhile, feel free to re-open it if you'd like to add additional commits to address the review comments.

-Donne

**Pull request closed without merging**
