### PR TITLE
Remove char challenge

### PR DESCRIPTION
**Pull request by mag6367**
Hi Donne, 

I believe the link to the solution manual will only link correctly when the pull request is merged.

Thanks :)

-Marco

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi Marco,

Thanks for the pull request, you're on a roll :)  

I have some catching up to do, I hope to review this in the next few days.

-Donne

**Comment by donnemartin** [comment]
Hi Marco,

Thanks for the pull request.  Here are some comments:

* This is a classic problem, although I believe typically it has a set of chars to remove, not just one char.  How do you feel about extending it to remove one or more chars instead of just one?
* For the remove_char solution, what do you think about providing a solution that doesn't call a built-in function?  For example, add the chars to remove in a hash map and use that as a lookup to determine which chars to remove.
* `remove_char_recur` is using `is` to check for value equality, where `is` is normally used to check reference equality.  See a more detailed discussion [here](http://stackoverflow.com/questions/132988/is-there-a-difference-between-and-is-in-python).
* One notebook is labeled Challenge, the other is Challenge Notebook
* The solution notebook has a solution notebook index link that's a dead link

-Donne

**Comment by mag6367** [comment]
Hi Donne, 

That stackflow question was very informative. Thank you! 

Let me work on this and I'll send the fixes. 

Have a good one

-Marco

**Comment by donnemartin** [comment]
Hi @mag6367, not sure if you're still interested in completing the changes suggested in this PR.  I'll be closing it soon unless I hear back.  Thanks.

**Comment by mag6367** [comment]
Hi Donne, hope you're doing well!

I've been incredibly busy with school and my internship that I totally
forgot about this. Give me some time, and I will try to fix these.

Thanks.

**Comment by donnemartin** [comment]
No problem!  I'll keep this open, thanks for the update.

**Comment by donnemartin** [comment]
Hi @mag6367 

I'm trying to clear out all PRs on this repo.  This PR hasn't had much activity in awhile, feel free to re-open it if you'd like to add additional commits to address the review comments.

-Donne

**Pull request closed without merging**
