### PR TITLE
added a simple challenge so that the user checks if list is sorted in…

### PR DESCRIPTION
**Pull request by mag6367**
… ascending order

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi Marco,

Awesome, thanks for the pull request!  I hope to review this and share some feedback in the next couple of days.

-Donne

**Comment by mag6367** [comment]
Hey donne I made another challenge (a bit simpler than the binary search tree) 
Let me know if I am on the right track or any feedback would be greatly appreciated. 

Thanks again

**Comment by donnemartin** [comment]
Hi Marco,

Sorry I've been a bit tied up recently, I should have time to review these tomorrow and provide feedback.  I'm excited to see what you've created :)

-Donne

**Comment by mag6367** [comment]
Donne, 

no problem man. Take your time.

Hope all is well :)

-Marco

**Comment by donnemartin** [comment]
Hi Marco,

Thanks again for submitting this pull request.  Here's some feedback for the reverse_words challenge:

* I think it is easier to review and approve pull requests if we have one challenge per pull request.  I'll update the [Contributing Guidelines](https://github.com/donnemartin/interactive-coding-challenges/blob/master/CONTRIBUTING.md).
* Please try to follow the template for notebooks outlined in the [Contributing Guidelines].(https://github.com/donnemartin/interactive-coding-challenges/blob/master/CONTRIBUTING.md)
* "Notebok written by Marco" contains a typo and is a different format from the other notebooks.
* The Constraints section is also different and isn't a Q&A style as you would typically see in an interview
* The Algorithm discussion is also a different format.  Is the time complexity really n = number of words or is it number of chars?  What is the space complexity?
* The code S = S.split() takes a string "S" and splits it into words, but re-uses the same variable "S".  This might be clearer as:
    * words = string.split()
* The unit test doesn't check for the case where None is passed in, as described in the Constraints section
* The unit test doesn't use the same format as the other notebooks.
* Please check the "Maintain Consistent Style" section of the [Contributing Guidelines](https://github.com/donnemartin/interactive-coding-challenges/blob/master/CONTRIBUTING.md) notebook about code style guidelines and PEP8.

-Donne

**Comment by donnemartin** [comment]
Hi Marco,

Regarding the binary tree challenge, here is some feedback:

* Please check out my comments from the reverse_words challenge, much of it applies to the binary tree challenge as well
* .DS_Store was checked in :)
* linked_list_solution and linked_list_challenge were checked in modified but don't have any real changes.

-Donne

**Comment by mag6367** [comment]
Hi Donne, 

Thank you so much for the feedback. I should have been more careful with the format of the notebooks, but I was sort of carried away with the actual code. I will make those fixes sometime in the next couple of days. 

As for the linked list, I added the is_sorted challenge. Which appears to need the format fixes as well. 

One question, for the unit test, you mean the print statement format? Or the actual code. 

Thanks again Donne

-Marco

**Comment by mag6367** [comment]
Hi Donne, 

I wanted to add that I believe the time complexity is O(n), where n is the number of words because the operation words[::-1] is O(1) and we only iterate over a string of words. Memory complexity is O(n) as well, but n is the number of chars.

**Comment by donnemartin** [comment]
Hi Marco,

>the operation words[::-1] is O(1)

I'm not sure this is accurate, can you point me to your reference?

The two references below seem to indicate each call to words[::-1] is O(k), where k is the slice size.  In this case it seems k = number of characters in the word.  For all words, the sum would appear to be O(n), where n is the number of characters.

http://stackoverflow.com/questions/13203601/big-o-of-list-slicing
https://wiki.python.org/moin/TimeComplexity#list

-Donne

**Comment by mag6367** [comment]
Hi Donne,

You are absolutely right. I was mistaken about the operation [::-1].
I'm going to fix that and prepare the notebooks correctly. 

-Marco

**Comment by mag6367** [comment]
I'm going to cancel this pull request and send you one challenge per request. I will begin with the reverse_words. 

Additionally, I will send the binary search challenge, but this one will take more time to fix entirely. 

Thanks again, Donne.

**Pull request closed without merging**
