### PR TITLE
Replaced "range(len(..))"style iteration with "in"

### PR DESCRIPTION
**Pull request by md5sam**
Mostly a cosmetic change - replaced explicit index-based looping with more Pythonic 'in' looping

### CODE REVIEW

**Comment by md5sam** [comment]
I might be wrong but are these challenge solutions intentionally written as range(len()) style to make it clear to programmers who are more familiar with C-style iteration, that we iterate from 0 to len(data) ?

**Comment by donnemartin** [comment]
Hi Samarth, thanks for the pull request!  I hope to review this within the next week or so.

**Comment by donnemartin** [comment]
@md5sam just want to let you know this is still on my radar.

**Comment by donnemartin** [comment]
@md5sam this change doesn't seem to pass the unit tests.  I'm getting the following error when I go to `Cell -> Run All`

```
None input
Empty input
One element
Two or more elements
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/Users/donnemartin/Dev/github/sources/interactive-coding-challenges/sorting_searching/quick_sort/test_quick_sort.py in <module>()
     33 
     34 if __name__ == '__main__':
---> 35     main()

/Users/donnemartin/Dev/github/sources/interactive-coding-challenges/sorting_searching/quick_sort/test_quick_sort.py in main()
     29 def main():
     30     test = TestQuickSort()
---> 31     test.test_quick_sort(quick_sort)
     32 
     33 

/Users/donnemartin/Dev/github/sources/interactive-coding-challenges/sorting_searching/quick_sort/test_quick_sort.py in test_quick_sort(self, func)
     22         data = [5, 1, 7, 2, 6, -3, 5, 7, -1]
     23         sorted_data = func(data)
---> 24         assert_equal(sorted_data, sorted(data))
     25 
     26         print('Success: test_quick_sort\n')

/Users/donnemartin/.pyenv/versions/3.4.3/lib/python3.4/unittest/case.py in assertEqual(self, first, second, msg)
    795         """
    796         assertion_func = self._getAssertEqualityFunc(first, second)
--> 797         assertion_func(first, second, msg=msg)
    798 
    799     def assertNotEqual(self, first, second, msg=None):

/Users/donnemartin/.pyenv/versions/3.4.3/lib/python3.4/unittest/case.py in assertListEqual(self, list1, list2, msg)
    993 
    994         """
--> 995         self.assertSequenceEqual(list1, list2, msg, seq_type=list)
    996 
    997     def assertTupleEqual(self, tuple1, tuple2, msg=None):

/Users/donnemartin/.pyenv/versions/3.4.3/lib/python3.4/unittest/case.py in assertSequenceEqual(self, seq1, seq2, msg, seq_type)
    975         standardMsg = self._truncateMessage(standardMsg, diffMsg)
    976         msg = self._formatMessage(msg, standardMsg)
--> 977         self.fail(msg)
    978 
    979     def _truncateMessage(self, message, diff):

/Users/donnemartin/.pyenv/versions/3.4.3/lib/python3.4/unittest/case.py in fail(self, msg)
    640     def fail(self, msg=None):
    641         """Fail immediately, with the given message."""
--> 642         raise self.failureException(msg)
    643 
    644     def assertFalse(self, expr, msg=None):

AssertionError: Lists differ: [-3, -1, 1, 2, 5, 6, 7] != [-3, -1, 1, 2, 5, 5, 6, 7, 7]

First differing element 5:
6
5

Second list contains 2 additional elements.
First extra element 7:
7

- [-3, -1, 1, 2, 5, 6, 7]
+ [-3, -1, 1, 2, 5, 5, 6, 7, 7]
?                   +++   +++
```

**Comment by donnemartin** [comment]
@md5sam are you still interested in updating this PR?

**Comment by donnemartin** [comment]
@md5sam I'm going to close this PR, please feel free to re-open it if you'd like to add additional commits to address the review comments.

**Pull request closed without merging**
