### PR TITLE
Coin Change Ways Problem/Solution

### PR DESCRIPTION
**Pull request by mrb00l34n**
Added new challenge and solution for the classic dp coin change problem (counting # of ways of making change). Please let me know if there are any issues.

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi mrb,

Thanks for the pull request!  I'll try to review it and provide feedback within the next few days.

-Donne

**Comment by donnemartin** [comment]
Hi mrb,

Nice work!  I have a couple requests for consideration:

-The argument ```k``` in function ```def change_ways(n,k,coins)``` doesn't seem to be used at all.
-Could you use ```range``` instead of ```xrange``` for Python 3 compatibility?
-It might be helpful to denote what ```n``` and ```m``` represent in the time complexity discussion for beginners.
-Can you tweak some of the whitespace between operators and function params?  I find http://pep8online.com is handy for notebook PEP8 validation.

-Donne

**Comment by mrb00l34n** [comment]
Thanks for the feedback. Fixed the above.

**Comment by donnemartin** [comment]
Great, I'll try to review this in the next day or two.

-Donne

**Comment by donnemartin** [comment]
Looking good!  I'll merge this later tonight.

**Comment by donnemartin** [comment]
Merged, thanks for the contribution!

**Pull request merged**
